version: '3.3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    container_name: zookeeper
    ports:
    - "2181:2181"
    environment:
    - ZOOKEEPER_CLIENT_PORT=2181
    networks:
    - kafka-twitter-example-network
    volumes:
    - kafka-twitter-example-volume-1:/var/lib/zookeeper/data
    - kafka-twitter-example-volume-2:/var/lib/zookeeper/log
  kafka:
    image: confluentinc/cp-kafka:5.0.0
    container_name: kafka
    ports:
    - "9092:9092"
    depends_on:
    - zookeeper
    environment:
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    networks:
    - kafka-twitter-example-network
    volumes:
    - kafka-twitter-example-volume-3:/var/lib/kafka/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch
    ports:
    - "9200:9200"
    environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
    - kafka-twitter-example-network
    volumes:
    - kafka-twitter-example-volume-4:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.3.0
    container_name: kibana
    ports:
    - "5601:5601"
    environment:
    - SERVER_NAME=localhost
    - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
    - kafka-twitter-example-network

networks:
  kafka-twitter-example-network:

volumes:
  kafka-twitter-example-volume-1:
  kafka-twitter-example-volume-2:
  kafka-twitter-example-volume-3:
  kafka-twitter-example-volume-4:
